risky: false

version: 8.1

preset: laravel

enabled:
  - const_visibility_required
  - method_argument_space_strict
  - new_with_braces
  - no_break_comment
  - psr12_braces
  - psr12_class_definition
  - single_trait_insert_per_statement

disabled:
  - class_definition
  - short_array_syntax
  - method_argument_space